server:
  port: 8080

rpcman:
  zk:
    enabled: false
    zkServer: localhost:2181
    zkRoot: rpcman

  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
    use-netty: true # open port = server.port + 1000

  provider:
    metas:
      dc: bj
      gray: false
      unit: B002
      tc: 300  # 流量控制器, 默认30s内访问20次


# apollo 配置中心
app:
  id: app
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true # 是否自动更新
  bootstrap:
    enabled: true
    namespaces: rpcman-app
    eagerLoad:
      enabled: false

# 作者手写的注册中心:https://github.com/ipipman/registry-man
registry-ipman:
  enabled: true
  servers: http://localhost:8484

logging:
  level:
    root: info
    cn.ipman.rpc: debug
    io.netty: info